### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/tweeting-babbage#10]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md

**Comment by lauraclay** [comment]
I've added everything I can to this one, including a blank learn.md. Let me know if it's all okay and I can get started on the others...
