### ISSUE TITLE
Copy editing

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/tweeting-babbage#14]
Hi @LornaLynch @lauraclay this has had the first half moved into the new GSW resource, and had some small changes in it, could just do with a once-over. The new version is in branch 'new'. See the worksheet here: https://github.com/raspberrypilearning/tweeting-babbage/blob/new/worksheet.md

Thanks

**Comment by LornaLynch** [comment]
I've made a couple of tweaks, but I think this is all fine.

**Comment by bennuttall** [comment]
@LornaLynch @lauraclay you've copy edited the **master** branch. The changes are in the **new** branch.

Please click this link and edit just that file: https://github.com/raspberrypilearning/tweeting-babbage/blob/new/worksheet.md

**Comment by LornaLynch** [comment]
Ok, that was definitely the right worksheet.
